name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Show directory structure
        run: ls -R

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Clean
        run: flutter clean
  
      - name: Pub get
        run: flutter pub get
        

      - name: Build APK (verbose)
        run: flutter build apk --release -v

 environment:
  sdk: '>=3.3.0 <4.0.0'
